using Lebenslauf.Api.Core.Data.Configuration;
using Lebenslauf.Api.Core.Data.Seeding;
using Lebenslauf.Api.Core.Data.Seeding.Configuration;
using Lebenslauf.Api.Features.Cv.Configuration;
using Lebenslauf.Api.Features.Cv.Contracts.Mediator.Requests;
using Microsoft.AspNetCore.Http;
using Microsoft.Extensions.Configuration;
using Shiny.Mediator;

// Feature endpoint namespaces
using Lebenslauf.Api.Features.Cv;

namespace Lebenslauf.Api.Core.Startup;

public static class ServiceCollectionExtensions
{
    public static IServiceCollection AddApiServices(this IServiceCollection services, IConfiguration configuration)
    {
        // Data (must be before features to register DbContext first)
        services.AddAppData(configuration);
        services.AddDataSeeding();

        services.AddShinyServiceRegistry();
        services.AddShinyMediator();

        // Features
        services.AddCvFeature();

        return services;
    }

    public static WebApplication MapEndpoints(this WebApplication app)
    {
        // Feature endpoints (generated by Shiny.Mediator.AspNet)
        app.MapGeneratedMediatorEndpoints(); // Lebenslauf.Api.Features.Cv

        // Custom file download endpoints
        app.MapCvExportEndpoints();

        return app;
    }

    private static void MapCvExportEndpoints(this WebApplication app)
    {
        var exportGroup = app.MapGroup("/api/cv");

        // PDF Export
        exportGroup.MapGet("/{profileSlug}/export/pdf", async (
            string profileSlug,
            IMediator mediator,
            CancellationToken ct) =>
        {
            var (_, response) = await mediator.Request(new ExportCvPdfRequest(profileSlug), ct);
            return Results.File(
                response.FileBytes,
                response.ContentType,
                response.FileName);
        })
        .WithName("ExportCvPdf")
        .WithDescription("Export CV as PDF document");

        // DOCX Export
        exportGroup.MapGet("/{profileSlug}/export/docx", async (
            string profileSlug,
            IMediator mediator,
            CancellationToken ct) =>
        {
            var (_, response) = await mediator.Request(new ExportCvDocxRequest(profileSlug), ct);
            return Results.File(
                response.FileBytes,
                response.ContentType,
                response.FileName);
        })
        .WithName("ExportCvDocx")
        .WithDescription("Export CV as Word document");

        // Also support export without profile slug (uses default)
        exportGroup.MapGet("/export/pdf", async (
            IMediator mediator,
            CancellationToken ct) =>
        {
            var (_, response) = await mediator.Request(new ExportCvPdfRequest(null), ct);
            return Results.File(
                response.FileBytes,
                response.ContentType,
                response.FileName);
        })
        .WithName("ExportCvPdfDefault")
        .WithDescription("Export default CV as PDF document");

        exportGroup.MapGet("/export/docx", async (
            IMediator mediator,
            CancellationToken ct) =>
        {
            var (_, response) = await mediator.Request(new ExportCvDocxRequest(null), ct);
            return Results.File(
                response.FileBytes,
                response.ContentType,
                response.FileName);
        })
        .WithName("ExportCvDocxDefault")
        .WithDescription("Export default CV as Word document");
    }

    public static async Task RunSeedersAsync(this WebApplication app)
    {
        using var scope = app.Services.CreateScope();
        var seederRunner = scope.ServiceProvider.GetRequiredService<SeederRunner>();
        await seederRunner.RunAllSeedersAsync();
    }
}
