using Lebenslauf.Api.Core.Data.Configuration;
using Lebenslauf.Api.Core.Data.Seeding;
using Lebenslauf.Api.Core.Data.Seeding.Configuration;
using Lebenslauf.Api.Features.Cv.Configuration;
using Microsoft.Extensions.Configuration;

// Feature endpoint namespaces
using Lebenslauf.Api.Features.Cv;

namespace Lebenslauf.Api.Core.Startup;

public static class ServiceCollectionExtensions
{
    public static IServiceCollection AddApiServices(this IServiceCollection services, IConfiguration configuration)
    {
        // Data (must be before features to register DbContext first)
        services.AddAppData(configuration);
        services.AddDataSeeding();

        services.AddShinyServiceRegistry();
        services.AddShinyMediator();

        // Features
        services.AddCvFeature();

        return services;
    }

    public static WebApplication MapEndpoints(this WebApplication app)
    {
        // Feature endpoints (generated by Shiny.Mediator.AspNet)
        app.MapGeneratedMediatorEndpoints(); // Lebenslauf.Api.Features.Cv

        return app;
    }

    public static async Task RunSeedersAsync(this WebApplication app)
    {
        using var scope = app.Services.CreateScope();
        var seederRunner = scope.ServiceProvider.GetRequiredService<SeederRunner>();
        await seederRunner.RunAllSeedersAsync();
    }
}