using Microsoft.Extensions.DependencyInjection;

namespace Lebenslauf.Core.ApiClient.Configuration;

/// <summary>
/// Extension methods for registering ApiClient services.
/// </summary>
public static class ServiceCollectionExtensions
{
    /// <summary>
    /// Adds the ApiClient feature services.
    /// Registers the generated OpenAPI HTTP handlers for Shiny.Mediator.
    /// </summary>
    public static IServiceCollection AddApiClientFeature(this IServiceCollection services)
    {
        // Register the generated OpenAPI HTTP handlers
        // This is generated by Shiny.Mediator's OpenApiHttpClientSourceGenerator
        services.AddGeneratedOpenApiClient();
        return services;
    }
}
